#include "vector"

#include "wasteWater/WasteWater_Treatment.h"
#include <emscripten/bind.h>

using namespace emscripten;

EMSCRIPTEN_BINDINGS(wasteWater_class)
{
    class_<WasteWater_Treatment::CalculationsTable>("CalculationsTable")
        .property("Se", &WasteWater_Treatment::CalculationsTable::Se)
        .property("HeterBio", &WasteWater_Treatment::CalculationsTable::HeterBio)
        .property("CellDeb", &WasteWater_Treatment::CalculationsTable::CellDeb)
        .property("InterVes", &WasteWater_Treatment::CalculationsTable::InterVes)
        .property("MLVSS", &WasteWater_Treatment::CalculationsTable::MLVSS)
        .property("MLSS", &WasteWater_Treatment::CalculationsTable::MLSS)
        .property("BiomassProd", &WasteWater_Treatment::CalculationsTable::BiomassProd)
        .property("SludgeProd", &WasteWater_Treatment::CalculationsTable::SludgeProd)
        .property("SolidProd", &WasteWater_Treatment::CalculationsTable::SolidProd)
        .property("Effluent", &WasteWater_Treatment::CalculationsTable::Effluent)
        .property("IntentWaste", &WasteWater_Treatment::CalculationsTable::IntentWaste)
        .property("OxygenRqd", &WasteWater_Treatment::CalculationsTable::OxygenRqd)
        .property("FlowMgd", &WasteWater_Treatment::CalculationsTable::FlowMgd)
        .property("NRemoved", &WasteWater_Treatment::CalculationsTable::NRemoved)
        .property("NRemovedMgl", &WasteWater_Treatment::CalculationsTable::NRemovedMgl)
        .property("NitO2Dem", &WasteWater_Treatment::CalculationsTable::NitO2Dem)
        .property("O2Reqd", &WasteWater_Treatment::CalculationsTable::O2Reqd)
        .property("EffNH3N", &WasteWater_Treatment::CalculationsTable::EffNH3N)
        .property("EffNo3N", &WasteWater_Treatment::CalculationsTable::EffNo3N)
        .property("TotalO2Rqd", &WasteWater_Treatment::CalculationsTable::TotalO2Rqd)
        .property("WAS", &WasteWater_Treatment::CalculationsTable::WAS)
        .property("EstimatedEff", &WasteWater_Treatment::CalculationsTable::EstimatedEff)
        .property("EstimRas", &WasteWater_Treatment::CalculationsTable::EstimRas)
        .property("FmRatio", &WasteWater_Treatment::CalculationsTable::FmRatio)
        .property("Diff_MLSS", &WasteWater_Treatment::CalculationsTable::Diff_MLSS)
        .property("SRT", &WasteWater_Treatment::CalculationsTable::SRT)
        .function("getArray", &WasteWater_Treatment::CalculationsTable::getArray);

    register_vector<WasteWater_Treatment::CalculationsTable>("CalculationsTableV");

    class_<WasteWater_Treatment::Output>("WasteWater_TreatmentOutput")
        .property("TotalAverageDailyFlowRate", &WasteWater_Treatment::Output::TotalAverageDailyFlowRate)
        .property("VolumeInService", &WasteWater_Treatment::Output::VolumeInService)
        .property("InfluentBOD5Concentration", &WasteWater_Treatment::Output::InfluentBOD5Concentration)
        .property("InfluentBOD5MassLoading", &WasteWater_Treatment::Output::InfluentBOD5MassLoading)
        .property("SecWWOxidNLoad", &WasteWater_Treatment::Output::SecWWOxidNLoad)
        .property("SecWWTSSLoad", &WasteWater_Treatment::Output::SecWWTSSLoad)
        .property("FM_ratio", &WasteWater_Treatment::Output::FM_ratio)
        .property("SolidsRetentionTime", &WasteWater_Treatment::Output::SolidsRetentionTime)
        .property("MLSS", &WasteWater_Treatment::Output::MLSS)
        .property("MLVSS", &WasteWater_Treatment::Output::MLVSS)
        .property("TSSSludgeProduction", &WasteWater_Treatment::Output::TSSSludgeProduction)
        .property("TSSInActivatedSludgeEffluent", &WasteWater_Treatment::Output::TSSInActivatedSludgeEffluent)
        .property("TotalOxygenRequirements", &WasteWater_Treatment::Output::TotalOxygenRequirements)
        .property("TotalOxygenReqWDenit", &WasteWater_Treatment::Output::TotalOxygenReqWDenit)
        .property("TotalOxygenSupplied", &WasteWater_Treatment::Output::TotalOxygenSupplied)
        .property("MixingIntensityInReactor", &WasteWater_Treatment::Output::MixingIntensityInReactor)
        .property("RASFlowRate", &WasteWater_Treatment::Output::RASFlowRate)
        .property("RASRecyclePercentage", &WasteWater_Treatment::Output::RASRecyclePercentage)
        .property("WASFlowRate", &WasteWater_Treatment::Output::WASFlowRate)
        .property("RASTSSConcentration", &WasteWater_Treatment::Output::RASTSSConcentration)
        .property("TotalSludgeProduction", &WasteWater_Treatment::Output::TotalSludgeProduction)
        .property("ReactorDetentionTime", &WasteWater_Treatment::Output::ReactorDetentionTime)
        .property("VOLR", &WasteWater_Treatment::Output::VOLR)
        .property("EffluentCBOD5", &WasteWater_Treatment::Output::EffluentCBOD5)
        .property("EffluentTSS", &WasteWater_Treatment::Output::EffluentTSS)
        .property("EffluentAmmonia_N", &WasteWater_Treatment::Output::EffluentAmmonia_N)
        .property("EffluentNO3_N", &WasteWater_Treatment::Output::EffluentNO3_N)
        .property("EffluentNO3_N_W_Denit", &WasteWater_Treatment::Output::EffluentNO3_N_W_Denit)
        .property("AeEnergy", &WasteWater_Treatment::Output::AeEnergy)
        .property("AeCost", &WasteWater_Treatment::Output::AeCost)
        .property("FieldOTR", &WasteWater_Treatment::Output::FieldOTR)
        .property("calculationsTable", &WasteWater_Treatment::Output::calculationsTable);

    class_<WasteWater_Treatment::OutputWithoutTable>("WasteWater_TreatmentOutputWithoutTable")
        .property("TotalAverageDailyFlowRate", &WasteWater_Treatment::OutputWithoutTable::TotalAverageDailyFlowRate)
        .property("VolumeInService", &WasteWater_Treatment::OutputWithoutTable::VolumeInService)
        .property("InfluentBOD5Concentration", &WasteWater_Treatment::OutputWithoutTable::InfluentBOD5Concentration)
        .property("InfluentBOD5MassLoading", &WasteWater_Treatment::OutputWithoutTable::InfluentBOD5MassLoading)
        .property("SecWWOxidNLoad", &WasteWater_Treatment::OutputWithoutTable::SecWWOxidNLoad)
        .property("SecWWTSSLoad", &WasteWater_Treatment::OutputWithoutTable::SecWWTSSLoad)
        .property("FM_ratio", &WasteWater_Treatment::OutputWithoutTable::FM_ratio)
        .property("SolidsRetentionTime", &WasteWater_Treatment::OutputWithoutTable::SolidsRetentionTime)
        .property("MLSS", &WasteWater_Treatment::OutputWithoutTable::MLSS)
        .property("MLVSS", &WasteWater_Treatment::OutputWithoutTable::MLVSS)
        .property("TSSSludgeProduction", &WasteWater_Treatment::OutputWithoutTable::TSSSludgeProduction)
        .property("TSSInActivatedSludgeEffluent", &WasteWater_Treatment::OutputWithoutTable::TSSInActivatedSludgeEffluent)
        .property("TotalOxygenRequirements", &WasteWater_Treatment::OutputWithoutTable::TotalOxygenRequirements)
        .property("TotalOxygenReqWDenit", &WasteWater_Treatment::OutputWithoutTable::TotalOxygenReqWDenit)
        .property("TotalOxygenSupplied", &WasteWater_Treatment::OutputWithoutTable::TotalOxygenSupplied)
        .property("MixingIntensityInReactor", &WasteWater_Treatment::OutputWithoutTable::MixingIntensityInReactor)
        .property("RASFlowRate", &WasteWater_Treatment::OutputWithoutTable::RASFlowRate)
        .property("RASRecyclePercentage", &WasteWater_Treatment::OutputWithoutTable::RASRecyclePercentage)
        .property("WASFlowRate", &WasteWater_Treatment::OutputWithoutTable::WASFlowRate)
        .property("RASTSSConcentration", &WasteWater_Treatment::OutputWithoutTable::RASTSSConcentration)
        .property("TotalSludgeProduction", &WasteWater_Treatment::OutputWithoutTable::TotalSludgeProduction)
        .property("ReactorDetentionTime", &WasteWater_Treatment::OutputWithoutTable::ReactorDetentionTime)
        .property("VOLR", &WasteWater_Treatment::OutputWithoutTable::VOLR)
        .property("EffluentCBOD5", &WasteWater_Treatment::OutputWithoutTable::EffluentCBOD5)
        .property("EffluentTSS", &WasteWater_Treatment::OutputWithoutTable::EffluentTSS)
        .property("EffluentAmmonia_N", &WasteWater_Treatment::OutputWithoutTable::EffluentAmmonia_N)
        .property("EffluentNO3_N", &WasteWater_Treatment::OutputWithoutTable::EffluentNO3_N)
        .property("EffluentNO3_N_W_Denit", &WasteWater_Treatment::OutputWithoutTable::EffluentNO3_N_W_Denit)
        .property("AeEnergy", &WasteWater_Treatment::OutputWithoutTable::AeEnergy)
        .property("AeCost", &WasteWater_Treatment::OutputWithoutTable::AeCost)
        .property("FieldOTR", &WasteWater_Treatment::OutputWithoutTable::FieldOTR);

    class_<WasteWater_Treatment>("WasteWater_Treatment")
        .constructor<double, double, double, double, double, double, double, double, double, double, double, double, double, double, double,
                double, double, double, double, double, double, double, double, double, double, double, int, double, double, double>()
        .function("calculate", &WasteWater_Treatment::calculate)
        .function("calculateGivenSRT", &WasteWater_Treatment::calculateGivenSRT);
}
